# Generated by Django 5.0.4 on 2026-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Инвентарный номер",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("PC", "Компьютер"),
                            ("Laptop", "Ноутбук"),
                            ("Printer", "Принтер"),
                            ("Other", "Прочее"),
                        ],
                        db_index=True,
                        default="PC",
                        max_length=20,
                        verbose_name="Тип устройства",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Процессор"
                    ),
                ),
                (
                    "ram",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ОЗУ (ГБ)"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("HDD", "HDD"),
                            ("SSD", "SSD"),
                            ("Mixed", "HDD + SSD"),
                            ("None", "Нет"),
                        ],
                        default="HDD",
                        max_length=10,
                        verbose_name="Тип накопителя",
                    ),
                ),
                (
                    "storage_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Объём накопителя (ГБ)"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Операционная система"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("broken", "Сломан"),
                            ("write_off", "Списан"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
                "ordering": ["inventory_number"],
            },
        ),
    ]
