# Generated by Django 5.0.4 on 2026-03-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="agent_hostname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя компьютера в сети, заполняется автоматически агентом.",
                max_length=255,
                verbose_name="Hostname (агент)",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="last_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя синхронизация"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="purchase_date",
            field=models.DateField(
                blank=True,
                help_text="Реальная дата покупки. Используется для расчёта возраста.",
                null=True,
                verbose_name="Дата приобретения",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="serial_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Серийный номер"
            ),
        ),
    ]
