# Generated by Django 5.0.4 on 2026-03-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Настройки системы', 'verbose_name_plural': 'Настройки системы'},
        ),
    ]
