# Generated by Django 5.0.4 on 2026-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_replacement_settings_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["inventory_number", "id"],
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
            },
        ),
        migrations.AlterModelOptions(
            name="systemsettings",
            options={
                "verbose_name": "Настройки системы",
                "verbose_name_plural": "Настройки системы",
            },
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="inventory_d_replace_9b7d25_idx",
            old_name="inventory_d_replace_8f7983_idx",
        ),
        migrations.RenameIndex(
            model_name="device",
            new_name="inventory_d_device__95973f_idx",
            old_name="inventory_d_device__9fb89d_idx",
        ),
        migrations.AlterField(
            model_name="device",
            name="agent_hostname",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Hostname (агент)"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="cpu_model",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Процессор"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="purchase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приобретения"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="storage_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Емкость диска (ГБ)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="pc_max_age_years",
            field=models.PositiveIntegerField(
                default=4, verbose_name="Макс. допустимый возраст ПК (лет)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="pc_min_ram_gb",
            field=models.PositiveIntegerField(
                default=8, verbose_name="Мин. допустимое ОЗУ (ГБ)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="pc_price_default",
            field=models.PositiveIntegerField(
                default=60000, verbose_name="Стоимость замены ПК по умолчанию (₽)"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="system_subtitle",
            field=models.CharField(
                blank=True,
                default="Учет компьютерной техники",
                max_length=200,
                verbose_name="Подзаголовок",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="system_title",
            field=models.CharField(
                default="IT Инвентарь", max_length=100, verbose_name="Название системы"
            ),
        ),
    ]
