# Generated by Django 5.0.4 on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_organization_address"),
        ("users", "0002_user_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
    ]
