# Generated by ChatGPT on 2026-03-31

from django.db import migrations, models
import django.db.models.functions.text
import re


def normalize_org(value: str) -> str:
    text = (value or "").strip().lower().replace("ё", "е")
    text = re.sub(r"[^0-9a-zа-я]+", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"\s+", " ", text).strip()
    for src, dst in (
        ("муниципальное бюджетное общеобразовательное учреждение", "мбоу"),
        ("муниципальное бюджетное учреждение", "мбу"),
        ("муниципальное казенное учреждение", "мку"),
        ("муниципальное казённое учреждение", "мку"),
        ("муниципальное автономное учреждение", "мау"),
        ("государственное бюджетное учреждение", "гбу"),
    ):
        if src in text:
            text = text.replace(src, dst)

    parts = text.split()
    if not parts:
        return ""

    if parts[0] in {"мку", "мбу", "мбоу", "мау", "гбу"}:
        legal = parts[0]
        rest = [p for p in parts[1:] if p not in {"им", "имени", "г", "города"}]
        if not rest:
            return legal
        if len(rest) == 1:
            return f"{legal} {rest[0]}"
        acronym = "".join(word[0] for word in rest if word)
        if acronym:
            return f"{legal} {acronym}"

    return " ".join(parts)


def fill_normalized_names(apps, schema_editor):
    Organization = apps.get_model("locations", "Organization")
    for org in Organization.objects.all().iterator():
        org.normalized_name = normalize_org(org.name)
        org.save(update_fields=["normalized_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название организации"),
        ),
        migrations.AddField(
            model_name="organization",
            name="normalized_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Нормализованное название"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(fill_normalized_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organization",
            name="normalized_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Нормализованное название"
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("normalized_name"),
                name="locations_org_normalized_name_ci_uniq",
            ),
        ),
    ]
