# Generated by ChatGPT on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_organization_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="Адрес"),
        ),
    ]
