# Generated by Django 5.0.4 on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_location"),
        ("locations", "0003_organization_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
